name: Build C program

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build C program
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build .
